spring:
    application:
        name: cetproAyne
    datasource:
        url: jdbc:mysql://localhost:3306/cetproAyne
        username: root
        password: 123456
        


server: 
    port: 8081
